action_dim: 7
action_model_type: DiT-B
data_root_dir: /fs-computility/efm/yejinhui/Projects/CogACT/playground/Datasets/OXE_openvla
future_action_window_size: 15
hf_token: HF_TOKEN
image_aug: true
is_resume: false
load_all_data_for_training: true
past_action_window_size: 0
pretrained_checkpoint: /fs-computility/efm/yejinhui/Projects/CogACT/playground/Pretrained_models/CogACT-Base/checkpoints/CogACT-Base.pt
repeated_diffusion_steps: 8
resume_epoch: null
resume_step: null
run_id: cogact_fullyFT_v1--image_aug
run_id_note: null
run_root_dir: /fs-computility/efm/yejinhui/Projects/CogACT/playground/Checkpoints
save_interval: 50
seed: 42
trackers:
- jsonl
- wandb
use_ema: false
vla:
  base_vlm: prism-dinosiglip-224px+7b
  data_mix: bridge
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
  epochs: 100
  expected_world_size: 1
  freeze_llm_backbone: false
  freeze_vision_backbone: false
  global_batch_size: 256
  learning_rate: 2.0e-05
  lr_scheduler_type: constant
  max_grad_norm: 1.0
  max_steps: null
  per_device_batch_size: 32
  reduce_in_full_precision: true
  shuffle_buffer_size: 250000
  train_strategy: fsdp-full-shard
  type: prism-dinosiglip-224px+oxe+diffusion
  unfreeze_last_llm_layer: false
  vla_id: prism-dinosiglip-224px+oxe+diffusion
  warmup_ratio: 0.0
  weight_decay: 0.0
wandb_entity: jinhuiye
wandb_project: two_system_vla
